Package structure, tests and workflows.
hifi/heisenbridge pull request #1
Opened 2021-04-15 11:50 UTC by tetov

2021-04-15 11:54 UTC, tetov commented
Tests on GH Actions pass.

https://github.com/tetov/unnamed-irc-bridge/actions/runs/751904035

2021-04-15 15:52 UTC, tetov commented
A bare bones package setup using setuptools and (nearly) [setup.cfg-only project](https://setuptools.readthedocs.io/en/latest/setuptools.html#id4). While more elegant solutions exists such as flit and poetry, this setup doesn't require any additional packages except the standard setuptools. 

I think a neater import structure should be implemented, but that will have to be in the next PR.

2021-04-16 05:35 UTC, hifi requested changes
Other than the wrong URL all this seems good. I'd like to name this project first, though so the temp name doesn't get embedded in so many places.

So if you don't mind let's figure out a name for this and merge after that?

2021-04-16 05:35 UTC, hifi commented on setup.cfg
> +url = https://github.com/hifi/unnamed_irc_bridge
This URL is wrong.

2021-04-16 09:44 UTC, merged